- name: Install Docker
  apt:
    name: docker.io
    state: present
    update_cache: yes

- name: Start and enable Docker
  systemd:
    name: docker
    enabled: yes
    state: started

- name: Install Docker Compose
  get_url:
    url: https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: '0755'

